# Generated by Django 3.1.5 on 2021-03-16 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_cerendials_clients_employee_franchise_images_machines_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cerendials',
            new_name='Crendials',
        ),
        migrations.RenameField(
            model_name='crendials',
            old_name='Cerendial_image',
            new_name='Crendial_image',
        ),
        migrations.RenameField(
            model_name='crendials',
            old_name='Cerendial_name',
            new_name='Crendial_name',
        ),
    ]
