# Generated by Django 3.1.5 on 2021-03-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210316_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='bg1_image',
            field=models.ImageField(blank='True', default='', upload_to='assests/upload'),
        ),
        migrations.AlterField(
            model_name='images',
            name='bg2_image',
            field=models.ImageField(blank='True', default='', upload_to='assests/upload'),
        ),
        migrations.AlterField(
            model_name='images',
            name='bg3_image',
            field=models.ImageField(blank='True', default='', upload_to='assests/upload'),
        ),
        migrations.AlterField(
            model_name='images',
            name='worker1_image',
            field=models.ImageField(blank='True', default='', upload_to='assests/upload'),
        ),
        migrations.AlterField(
            model_name='images',
            name='worker2_image',
            field=models.ImageField(blank='True', default='', upload_to='assests/upload'),
        ),
        migrations.AlterField(
            model_name='images',
            name='worker3_image',
            field=models.ImageField(blank='True', default='', upload_to='assests/upload'),
        ),
    ]
